version: "3"

services:
  mysql:
    image: mysql:5.7 # Mysql image
    container_name: dog_mysql
    volumes: # 호스트 디렉토리와 컨테이너 디렉토리 연결
      - ./mysql/mysqldata:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment: # 컨테이너 안의 환경변수 설정
      - MYSQL_ROOT_PASSWORD=root!@#
      - MYSQL_DATABASE=dog_poll
    ports: # 호스트와 컨테이너 포트 매핑
      - "13306:3306"
    restart: unless-stopped # 컨테이너 다운 시 항상 재시작
  redis:
    image: redis
    container_name: dog_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
